### ISSUE TITLE
notification critical

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#100]
08/03/2019 18:31:32 [Critical]: https://esi.evetech.net/latest/characters/1080995199/notifications/?datasource=tranquility&language=en-us 
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ThunderED.Helpers.APIHelper.ESIRequestWrapper[T](String request, String reason, String auth, String etag, Boolean noRetries, Boolean silent) in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Helpers\APIHelper.cs:line 92

**Comment by panthernet** [comment]
Probably query error if notifications work after this
