### ISSUE TITLE
Discord Notification Embed Error

### ISSUE THREAD

**Issue by MindlessPuppetz** [panthernet/ThunderED#15]
I am working with the notification templates, and have come across a few things that will break the system if used to try and format them a bit further.

`\n`
`\\n`
`: (colon)`
`\:`
`\\:`

These characters inside of the following line will cause the below error.

**LINE**
`#if !{isNpcKill} .AddField(" ", "**{victimName}({victimCorpName}{victimAllyTicker})** lost their **{shipType}** in {systemName}({systemSec}). Final blow by **{attackerName}({attackerCorpName} {attackerAllyTicker})**")
`

**ERROR**
`08/01/2018 01:16:11 [Critical]: The server responded with error 400: BadRequest 
Discord.Net.HttpException: The server responded with error 400: BadRequest
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options)
   at ThunderED.API.DiscordAPI.SendMessageAsync(IMessageChannel channel, String message, Embed embed)
   at ThunderED.API.DiscordAPI.SendMessageAsync(IMessageChannel channel, String message, Embed embed)
   at ThunderED.Classes.TemplateHelper.PostTemplatedMessage(MessageTemplateType type, Dictionary`2 dic, UInt64 channelId, String message)
   at ThunderED.Modules.OnDemand.RadiusKillFeedModule.ProcessKill(ZKillboard kill)
`

Discord Embeds themselves do support the usage of `\n` as tested at https://leovoel.github.io/embed-visualizer/

**Comment by panthernet** [comment]
Okay I've checked this and seems like I have no exception on \n insert or any other combination you mentioned. Anyway new line weren't working as expected so I've added **{NewLine}** param to the latest commit. Now it is correctly replaced by line break.

Feel free to check it and let me know if it workds for you.

By the way, there is an easier way to check it. There is a special command to generate fake KM based on the template:
**!test km true** 

It uses Template.killMailGeneral.txt placed in Templates/Messages folder for the output. (TestModule.cs file)
