### ISSUE TITLE
Corp / char command critical

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#73]
Some corp or character returns critical error and log entry like:
05/28/2019 08:56:44 [Critical]: corp 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ThunderED.Modules.Static.CorpSearchModule.CorpSearch(ICommandContext context, String name) in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Modules\Static\CorpSearchModule.cs:line 35
   at ThunderED.Classes.DiscordCommands.Corp(String x) in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Classes\DiscordCommands.cs:line 1251

**Comment by panthernet** [comment]
@srobi can you give me an example search string which fails?

**Comment by srobi** [comment]
Corp ticker: gepro

**Comment by panthernet** [comment]
Fixed in V1.3.14
