### ISSUE TITLE
ward declaration - critical error in notification

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#99]
08/01/2019 07:59:27 [Critical]: Error Notification: WarDeclared - againstID: 99002107
cost: 100000000
declaredByID: 99009348
delayHours: 24
hostileState: false
timeStarted: 132090505200000000
warHQ: <b>Perimeter - quan fu wu cha bie xuan zhan</b>
warHQ_IdType:
- 1031068245078
- 35833

 
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at ThunderED.LM.Get(String key, Object[] prms) in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Classes\LM.cs:line 69
   at ThunderED.Modules.NotificationModule.NotificationFeed() in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Modules\NotificationModule.cs:line 822

**Comment by panthernet** [comment]
Make sure you've updated the `notifWarDeclared` text

**Comment by srobi** [comment]
using the last build you published: 
"notifWarDeclared": "{0} has declared war on {1}!",

**Comment by panthernet** [comment]
Nope, it has `HQ: {2}` at the end

**Comment by srobi** [comment]
latest dropbox pre-release line 583 
"notifWarDeclared": "{0} has declared war on {1}!",

**Comment by panthernet** [comment]
I'm sorry, forgot about pre-release version you use :( Will make a new one once I'll finish current investigation.
